// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// The country code from ISO 3166 find more at https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
type CountryCode = string

// The currency code from ISO 4217 find more at https://en.wikipedia.org/wiki/ISO_4217
type CurrencyCode = string

// GenericError defines model for generic-error.
type GenericError struct {
	Code        *string `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
}

// Id defines model for id.
type Id = string

// RequestCancellation defines model for request-cancellation.
type RequestCancellation struct {
	AcquirerCode      *Id `json:"acquirer_code,omitempty"`
	AuthorizationCode *Id `json:"authorization_code,omitempty"`

	// The country code from ISO 3166 find more at https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
	CountryCode *CountryCode `json:"country_code,omitempty"`

	// The currency code from ISO 4217 find more at https://en.wikipedia.org/wiki/ISO_4217
	CurrencyCode    *CurrencyCode `json:"currency_code,omitempty"`
	MerchantCode    *Id           `json:"merchant_code,omitempty"`
	TransactionData *struct {
		TransactionId   *Id     `json:"transaction_id,omitempty"`
		TransactionType *string `json:"transaction_type,omitempty"`
	} `json:"transaction_data,omitempty"`
}

// RequestReversal defines model for request-reversal.
type RequestReversal struct {
	AcquirerCode      *Id `json:"acquirer_code,omitempty"`
	AuthorizationCode *Id `json:"authorization_code,omitempty"`

	// The country code from ISO 3166 find more at https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
	CountryCode *CountryCode `json:"country_code,omitempty"`

	// The currency code from ISO 4217 find more at https://en.wikipedia.org/wiki/ISO_4217
	CurrencyCode    *CurrencyCode `json:"currency_code,omitempty"`
	MerchantCode    *Id           `json:"merchant_code,omitempty"`
	TransactionData *struct {
		TransactionId   *Id     `json:"transaction_id,omitempty"`
		TransactionType *string `json:"transaction_type,omitempty"`
	} `json:"transaction_data,omitempty"`
}

// RequestTransaction defines model for request-transaction.
type RequestTransaction struct {
	AcquirerCode      *Id `json:"acquirer_code,omitempty"`
	AuthorizationCode *Id `json:"authorization_code,omitempty"`

	// The country code from ISO 3166 find more at https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
	CountryCode *CountryCode `json:"country_code,omitempty"`

	// The currency code from ISO 4217 find more at https://en.wikipedia.org/wiki/ISO_4217
	CurrencyCode    *CurrencyCode `json:"currency_code,omitempty"`
	MerchantCode    *Id           `json:"merchant_code,omitempty"`
	TransactionData *struct {
		Amount          *float32 `json:"amount,omitempty"`
		TransactionType *string  `json:"transaction_type,omitempty"`
		WithPassword    *bool    `json:"with_password,omitempty"`
	} `json:"transaction_data,omitempty"`
}

// ResponseTransactions defines model for response-transactions.
type ResponseTransactions struct {
	RegisteredAt  *time.Time `json:"registered_at,omitempty"`
	TransactionId *Id        `json:"transaction_id,omitempty"`
}

// N201Success defines model for 201-success.
type N201Success = ResponseTransactions

// N400BadRequest defines model for 400-bad-request.
type N400BadRequest = GenericError

// N401Unauthorized defines model for 401-unauthorized.
type N401Unauthorized = GenericError

// N403Forbidden defines model for 403-forbidden.
type N403Forbidden = GenericError

// N500Unavailable defines model for 500-unavailable.
type N500Unavailable = GenericError

// CreateTransactionJSONBody defines parameters for CreateTransaction.
type CreateTransactionJSONBody = RequestTransaction

// RequestCancellationJSONBody defines parameters for RequestCancellation.
type RequestCancellationJSONBody = RequestCancellation

// RequestReversalJSONBody defines parameters for RequestReversal.
type RequestReversalJSONBody = RequestReversal

// CreateTransactionJSONRequestBody defines body for CreateTransaction for application/json ContentType.
type CreateTransactionJSONRequestBody = CreateTransactionJSONBody

// RequestCancellationJSONRequestBody defines body for RequestCancellation for application/json ContentType.
type RequestCancellationJSONRequestBody = RequestCancellationJSONBody

// RequestReversalJSONRequestBody defines body for RequestReversal for application/json ContentType.
type RequestReversalJSONRequestBody = RequestReversalJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /transactions)
	CreateTransaction(ctx echo.Context) error

	// (POST /transactions/{id}/cancellation)
	RequestCancellation(ctx echo.Context, id Id) error

	// (POST /transactions/{id}/reversal)
	RequestReversal(ctx echo.Context, id Id) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CreateTransaction converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTransaction(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateTransaction(ctx)
	return err
}

// RequestCancellation converts echo context to params.
func (w *ServerInterfaceWrapper) RequestCancellation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RequestCancellation(ctx, id)
	return err
}

// RequestReversal converts echo context to params.
func (w *ServerInterfaceWrapper) RequestReversal(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RequestReversal(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/transactions", wrapper.CreateTransaction)
	router.POST(baseURL+"/transactions/:id/cancellation", wrapper.RequestCancellation)
	router.POST(baseURL+"/transactions/:id/reversal", wrapper.RequestReversal)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZTW/bOBP+K8K8vb1iTEm2bOuWFotFgAJdpN1TN2tQ5Mhma5EqSbfNGv7vC8qOra9k",
	"nUWawzY3fcwXZ55nrBlvgeuy0gqVs5BtwaCttLJY38Q0InbDOdr6lmvlUDl/yapqLTlzUqvRJ6uVf2b5",
	"Ckvmr14ZLCCD/41Otkf7t3Z054A4w5Rl3JuwsNvtQhBouZGVfwIZwC6EMaUkZ4IY/LJB654siCUqNJIT",
	"NEab+51HZKPYxq20kX+heG7vCSm0yaUQqJ7X9YRSf/CvTK5ZvsbndL4LD7YOgNsoZ24XXIs6irb0hxUG",
	"B4nASwSF0WVw9f5dkERpGhRSiaDUBgPmgpVzlc1GI1QX3+RnWaGQ7EKb5cjfjd5K6xa6WFy9f7fwuoum",
	"Y/uHghDwOysrnwu4vP4VQijZ97eolm4FWRJCKVXjzt1WXtA6I9XSJ5RvjEHFHzzIQaRzknEcTR9zEn8C",
	"r9OJ+Zffrx8bc7tY2fZkzdfFHwMojaBbwlo8KNFatkRvpzK6QuMk2pPmtu+uZaX3fheCk64+SjuuY+A6",
	"/4TceUtStKKFMc9pns6R4DgXZJwWKclpFJEZFxMRi2SejvNOctJ2dtIQKuYcGn/APz9SMmekuNnOduR4",
	"PT7jOop3r2Ag04fmRjhTHNdrdpeDRsIZ/7KRBs0BQJBP0+mczSihnMYkilCQ2ZQWZJqk8zSNZxOKDEK4",
	"6121yZbufBq3dZHQXMwLJpKUplMIO9yD19eX0APy3lZO27aihNBijBEiTyc1REo0fMWUa4fPZm01SqKE",
	"xZSKyZwmXq3xC7EQzNX9pfnMVxpYHE9Q5HUqkr0thjQhPBGzgs6nPC6Kjq1DBVr53vWg2sn5w61NCl/J",
	"oXyfo9ftcw9ptGSHesuDyi3hXa8y5wQ7VJV25ro1eqzVfX0Gm0Cb7I22MEiige5wJ2fwKxrL1i9E+/FE",
	"O+b6hWT/DZIdC/oAwRq+Xjh2D8dY6eOCLE6i4V8og0I6COGbdKtFxaz9po2AzJkNvnDp6bh0V4cjG9Sm",
	"zNGcSZleeY4SudZrZOpMVjUZM0isocG5TS2DS2kdGhQL5iCDmMYxoVMSTz5ENBuPs2j2f0op7eDx0N8p",
	"TemcexynexzPYzoh06RIJ3TC4jyZ9D/oOx63UGhT1r4Fc0icLHHom/fx3auVsKFM9FPshwFV6P7Adfnb",
	"lQ2cDgxylF8xwO/+456tgxYf7H4Me83U57WGk/vLA8+C2gwTrHLoJxHfE/f2owt6Qf0xdYWKVRIySC7o",
	"RQz1ILGqEzfqlrHS+wWHz27t/8pX5Y1B5vBDCxoHwLzW4vYJ1zJ9ENYZ9C+kwbuuE/Y2RPdZPsqNmmuk",
	"/VLnn3W6m5/9PuYcvc7SZr9K+XeKk3Mi7W5LaqSypYXsI7RqfOPftMo+2kqxG3XnvmEgXO8T8ab9fVsx",
	"w0p0aLy7LswbrgIpPOA9Pm6Do2HwBIGsBiWEoFjp8S0FdMsenomimqg3PxahnbHtp4JocyX4bPhsjkoP",
	"YvP69Fn4E+KyMeW8YPIJMXl61dubNiRP4LEnxLT/YrjZ/R0AAP//Fy4HuO0YAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
