apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name:  {{ include "banklo-authorizer-adapter.fullname" . }}
spec:
  host:  {{ include "banklo-authorizer-adapter.fullname" . }}
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2