{{- if .Values.ingress.enabled -}}
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: banklo-authorizer-adapter-do-not-preserve-host
route:
  preserve_host: false
upstream:
  host_header: {{ include "banklo-authorizer-adapter.fullname" . }}.cards.svc
{{end}}