apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "banklo-authorizer-adapter.fullname" . }}
spec:
  hosts:
    - {{ include "banklo-authorizer-adapter.fullname" . }}
  http:
    - fault:
        delay:
          percent: 50
          fixedDelay: 3s
      route:
        - destination:
            host: {{ include "banklo-authorizer-adapter.fullname" . }}
            subset: v1