apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "banklo-authorizer-adapter.fullname" . }}
spec:
  hosts:
    - {{ include "banklo-authorizer-adapter.fullname" . }}
  http:
    - route:
        - destination:
            host: {{ include "banklo-authorizer-adapter.fullname" . }}
            subset: v1
          weight: 80
        - destination:
            host: {{ include "banklo-authorizer-adapter.fullname" . }}
            subset: v2
          weight: 20
          fault:
            delay:
              fixedDelay: 3s
              percentage: 100