// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	adapter2 "github.com/modern-apis-architecture/banklo-authorizer-adapter/internal/adapter"
	"github.com/modern-apis-architecture/banklo-authorizer-adapter/internal/domain/adapter"
)

// Injectors from wire.go:

func BuildAppContainer() (*adapter.TransactionHttpAdapter, error) {
	ledgerService := adapter2.NewLedgerService()
	transactionHttpAdapter := adapter.NewTransactionHttpAdapter(ledgerService)
	return transactionHttpAdapter, nil
}
