// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/modern-apis-architecture/banklo-authorizer-adapter/internal/adapter"
	"github.com/modern-apis-architecture/banklo-authorizer-adapter/internal/ledger/client"
)

// Injectors from wire.go:

func BuildAppContainer() (*adapter.TransactionHttpAdapter, error) {
	ledgerServiceClient := client.ProvideLedgerServiceClient()
	internalLedgerService := client.NewInternalLedgerService(ledgerServiceClient)
	transactionHttpAdapter := adapter.NewTransactionHttpAdapter(internalLedgerService)
	return transactionHttpAdapter, nil
}
